Update to JavaScriptCore 4.1/Move the main code to main folder/Update to 2021 edition
tauri-apps/javascriptcore-rs pull request #69
Opened 2022-11-25 17:38 UTC by mrquantumoff

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ X ] Refactor
- [ X ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No
- [ ] I'm not sure, I just updated javascriptcoregtk from 4.0 to 4.1 and reorganized the folder structure

### Checklist
- [ X ] When resolving issues, they are referenced in the PR's title (e.g `fix #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ X ] I have added a convincing reason for adding this feature

### Other information

In order to package an app for flatpak without sacrificing new security/other features  and user's hard disk space by using an older runtime this package would need an update to JavaScriptCore 4.1

2022-11-25 20:00 UTC, FabianLars commented
Thanks for contributing!

To be honest, i am not a fan of the new folder, primarily because the old layout seems to be the default in similar crates as far as i can see.

Also we should probably release 4.0 with `0.16` dependencies first, and then this so that we can keep all 3 versions around (we need 4.0 + 0.15 for Tauri for example) -> This is more of a message to the other maintainers.

There may be a bit delay until Yu-Wei reviews it because we're quite busy right now and aren't completely sure yet what the best upgrade strategy would be.

2022-11-25 20:21 UTC, mrquantumoff commented
> Thanks for contributing!
> 
> To be honest, i am not a fan of the new folder, primarily because the old layout seems to be the default in similar crates as far as i can see.
> 
> Also we should probably release 4.0 with `0.16` dependencies first, and then this so that we can keep all 3 versions around (we need 4.0 + 0.15 for Tauri for example) -> This is more of a message to the other maintainers.
> 
> There may be a bit delay until Yu-Wei reviews it because we're quite busy right now and aren't completely sure yet what the best upgrade strategy would be.

Ok, I'll reverse the whole new folder thing when I get the chance, I'll wait as much as I'll have to, I get that maintaining OSS isn't as easy as many people think it is

2022-11-26 04:35 UTC, wusyong commented on .github/workflows/build.yml
> +          sudo apt-get install -y webkit2gtk-4.1
I think we can publish a minor version with 2021 edition and using glib 0.16.
But we might need to stick in webkit2gtk-4.0 as many old distribution might not have 4.1
We'll look into 4.1 after we switch to flatpak for packaging and CICD.

```suggestion
          sudo apt-get install -y webkit2gtk-4.0
```

2022-11-26 09:22 UTC, wusyong requested changes
Just need to revert a few version changes and I think it should pass the CI.

2022-11-26 09:22 UTC, wusyong commented on sys/Cargo.toml
> +version = "2.38"
```suggestion
name = "javascriptcoregtk-4.0"
version = "2.24"
```

2022-11-26 09:22 UTC, wusyong commented on sys/tests/abi.rs
> +static PACKAGES: &[&str] = &["javascriptcoregtk-4.1"];
```suggestion
static PACKAGES: &[&str] = &["javascriptcoregtk-4.0"];
```

2022-11-26 09:22 UTC, wusyong commented on Gir.toml
> +version = "4.1"
```suggestion
version = "4.0"
```

2022-11-26 09:22 UTC, wusyong commented on Gir.toml
> +min_cfg_version = "2.38"
```suggestion
min_cfg_version = "2.24"
```

2022-11-26 09:51 UTC, wusyong approved these changes

2022-11-26 09:51 UTC, merged